version: "3.7"
services:
    app:
        build:
            args:
                user: admin
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: jpcs
        container_name: cspc-jpcs-web
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - jpcs
        command: sh -c "composer install --ignore-platform-reqs && php artisan key:generate"


    db:
        image: mysql:8.3
        container_name: cspc-jpcs-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - jpcs
    nginx:
        image: nginx:alpine
        container_name: cspc-jpcs-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - jpcs
networks:
    jpcs:
        driver: bridge
